# SITE SETTINGS
title: Peatland restoration guidelines
author: ALFAwetlands
baseurl: "/restoration-guidelines"

# THEME SETTINGS
remote_theme: peterdesmet/petridish@3.1
github_edit: false
colors:
  links: "#0F71B8"  # Blue
  banner: "#6B9080" 
  footer: "#6B9080" # Jungle teal
font_serif: false
rounded_corners: true
logo: /assets/images/created_logo.png

# BUILD SETTINGS
repository: ALFAwetlands/restoration-guidelines
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
exclude:
 - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - petridish-3.1/
  - petridish.zip

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: pages/peatlands
    values:
      toc: true
      permalink: pages/peatlands